### ISSUE TITLE
Code is prompting to create a custom date field

### ISSUE THREAD

**Issue by IDSUK** [braini75/gantt_extension#2]
I am assuming that this may be the "fix" in the readme doc.
Could you expand on this a bit more please?
"Attention!! This plugin extends core function!

If your Redmine Version is not working you can try to update the file /path/to/redmine/plugins/gantt_extension/lib/gantt.rb so that those functions matches with the core functions in /path/to/redmine/lib/redmine/helpers/gantt.rb and the additional attribute 'custom_date' in def line()."

**Comment by braini75** [comment]
No!
The line you quoted is just developing Information, to get the plugin running with unsupported Versions of redmine.

The message "Please create first a custom field with Type 'date'" is exactly what it says! You have to create a custom-field first, before you can use the functionality of this plugin! To create a custom-field go to Administration and find the option there.
The plugin needs to know, with custom-field you would like to display (setup with Administration->Plugins->gantt_extension).
